# Generated by Django 5.2.5 on 2025-08-21 18:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(max_length=100)),
                ('color_hex', models.CharField(max_length=7)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('vendor', models.CharField(blank=True, max_length=100)),
                ('base_monthly_cost', models.DecimalField(decimal_places=2, help_text="Coût mensuel de base de l'outil (licence)", max_digits=10)),
                ('website_url', models.URLField(blank=True)),
                ('owner_department', models.CharField(choices=[('EN', 'Engineering'), ('SA', 'Sales'), ('MK', 'Marketing'), ('HR', 'HR'), ('FI', 'Finance'), ('OP', 'Operations'), ('DE', 'Design')], max_length=2)),
                ('status', models.CharField(choices=[('AC', 'Active'), ('TR', 'Trial'), ('DE', 'Deprecated')], default='AC', max_length=2)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tools', to='toolsmanagement.category')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CostTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('month_year', models.DateField(help_text='Mois/année du suivi de coût')),
                ('total_monthly_cost', models.DecimalField(decimal_places=2, help_text='Coût mensuel total incluant licence + surcoûts', max_digits=10)),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_tracking', to='toolsmanagement.tool')),
            ],
            options={
                'verbose_name': 'Suivi de coût mensuel',
                'verbose_name_plural': 'Suivis de coûts mensuels',
                'ordering': ['-month_year'],
                'unique_together': {('tool', 'month_year')},
            },
        ),
        migrations.CreateModel(
            name='AccessRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_justification', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('processing_notes', models.TextField(blank=True)),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requests_processed', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_requests', to=settings.AUTH_USER_MODEL)),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_requests', to='toolsmanagement.tool')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'tool', 'status')},
            },
        ),
        migrations.CreateModel(
            name='UsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session_date', models.DateField()),
                ('usage_minutes', models.IntegerField()),
                ('actions_count', models.IntegerField()),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_logs', to='toolsmanagement.tool')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-session_date'],
                'unique_together': {('tool', 'user', 'session_date')},
            },
        ),
        migrations.CreateModel(
            name='UserToolAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('granted_at', models.DateTimeField()),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('granted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accesses_granted', to=settings.AUTH_USER_MODEL)),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accesses_revoked', to=settings.AUTH_USER_MODEL)),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_accesses', to='toolsmanagement.tool')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_accesses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-granted_at'],
                'unique_together': {('user', 'tool')},
            },
        ),
    ]
