# Generated by Django 5.2.5 on 2025-08-21 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolsmanagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='vendor',
            field=models.CharField(max_length=100),
        ),
    ]
