# Generated by Django 5.2.5 on 2025-08-22 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolsmanagement', '0002_alter_tool_vendor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='costtracking',
            options={'ordering': ['-month_year'], 'verbose_name': 'Monthly cost tracking'},
        ),
        migrations.AddField(
            model_name='accessrequest',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accessrequest',
            name='status',
            field=models.CharField(choices=[('PE', 'Pending'), ('AP', 'Approved'), ('RE', 'Rejected')], default='pending', max_length=2),
        ),
    ]
